### ISSUE TITLE
Black Screen on serial log

### ISSUE THREAD

**Issue by MasterTimAX** [danak6jq/RAK3172#1]
Hi Dana! Thank you so much for this contribution!

Im from Brazil and tested your code. I compiled with stm32cubeIde version 1.9.0 and i dont now with this chip don't work. 
im programmer this chip with stlink v2 but i still have a issue. 

Could you please help-me?

**Comment by danak6jq** [comment]
Have you done other STM32 projects with STM32CubeIDE ?

**Comment by MasterTimAX** [comment]
Hi danak6jq! Thanks for you reply. The issue happened because i did not configure the lorawan_conf.h with the same parameters as lora_app.h. 

Best Regards
