### ISSUE TITLE
Cannot get External Interrupt working on PB5

### ISSUE THREAD

**Issue by Th3B1gKahuna** [danak6jq/RAK3172#2]
Hi Dana,

Quick "interrupt" :-)  Thanks for the great code.  Much appreciated.  I'm currently using the RAK3172 on the RAK5005 with an SHTC3 temp/humidity sensor.  All my LoRaWAN functions work with no problem.  I'm sending data up to a local gateway using Cayenne_LPP.

I've been trying to set up pin PB5 to receive an external interrupt with no success.  I'm been working on this for days and I'm out of ideas.  The code I'm using was working on a different STM32 End-Node software package with this identical hardware.  For some reason, I'm never getting into the interrupt callback function.    NVIC is enabled for the pin. EXTI9_5_IRQHandler is defined.

However, I can't verify where CubeMX is actually generating the pin definition code and placing it in the source tree. (PB5, pull-up resistor and negative edge triggering).  I'm accustomed to finding this init code in main.c

Any ideas how to debug this further?

Thanks,

Glenn.

**Comment by danak6jq** [comment]
@Th3B1gKahuna Hey Glenn, there's a gotcha in the ST LoRaWAN stack - it defers port (and other) initialization into the LoRaWAn application code, so you need to do it yourself, maybe in LoRaWAN_Init() or some BSP function like BSP_RSK5005_Init() , somewhere near that in program flow.

In the CubeMX Program Manager > Advanced Settings, you'll see that 'Generate Code' is unchecked for MX_GPIO_Init
<img width="513" alt="image" src="https://user-images.githubusercontent.com/942815/169895903-bf430f23-ed99-4d39-b699-f9382780640c.png">

So you're not going bonkers, CubeMX is simply not initializing PB5 for you. Let me know if this helps.

**Comment by Th3B1gKahuna** [comment]
Wow - I completely missed the unchecked box to generate the GPIO code.  I made the change and everything is now working great.  Thanks for the explanation and quick response.  So good to have another set of eyes helping out:-)

**Comment by danak6jq** [comment]
I'm glad I could help. The structure of the ST LoRaWAN app is different than normal CubeMX apps - no doubt inherited from the Semtech LoRaWAN stack upstream.

Have fun!
