### ISSUE TITLE
HSEO is 32M?

### ISSUE THREAD

**Issue by IoTopenTech** [danak6jq/RAK3172#3]
I'm trying to understand this port.
The IOC file shows an 8M HSEO but, according to the RAK3172 datasheet, it should be a 32M one.
![imagen](https://user-images.githubusercontent.com/52624907/175878317-0b379c80-48a2-442c-82de-f8991b847f9a.png)
I don't know whether this is relevant, but would like to understand it.
Kind regards from Madrid

**Comment by IoTopenTech** [comment]
According to this forum post (https://forum.rakwireless.com/t/hse32-tcxo-or-xtal/4764/7) it seems to be a 32MHz regular (no TCXO) crystal

**Comment by DominusFulguris** [comment]
The .ioc file still set to 8MHz for the HSEO.

I think the clock config should be 32MHz for HSE, then PLL Source Mux set to HSESystem Clock Mux to PLLCLK.  PLLM values /2, X6, /2

Or have I got this mixed up somehow?
