### ISSUE TITLE
On Timer Event

### ISSUE THREAD

**Issue by IvanAmg** [danak6jq/RAK3172#6]
Hi @danak6jq  !
First, I want to thank you for such an amazing contribution.
I tested the original example on the STM32 Nucleo board and worked like a charm (as it should be), then, I was able to see the values sent periodically. 
Then I switched to the RAK3172 chip in a custom board, thus, I found your repo looking for the updated version for this End Node example.
I'm currently testing this code example with these configurations:
- Activation by ABP
- Region US915
- Class A
- Send Tx on timer (as the title says).
- APP_TX_DUTYCYCLE of 10s (default value).
The issue is that when Tx data is being sent, it stops sending data after a few seconds.
Even if the right subband is found, the data is sent just one or two times.
Any new idea to try would be so much help.
Again, thank you so much for your contribution to this chip!

**Comment by Th3B1gKahuna** [comment]
The code is working fine for me using the RAK3172 on the RAK5005 board.  I'm using the code based on the 1.1 SDK.  I understand that there might be newer code out there.

Below are the defines I'm using in my lora_app.h file.  Note that I'm using class C along with confirmed messages.  BTW - I'm also using the RAK7268 gateway which took me a while get set up properly.  Here are my defines:

#define ACTIVE_REGION                               LORAMAC_REGION_US915
#define APP_TX_DUTYCYCLE                            120000
#define LORAWAN_USER_APP_PORT                       2
#define LORAWAN_SWITCH_CLASS_PORT                   3
#define LORAWAN_DEFAULT_CLASS                       CLASS_C
#define LORAWAN_DEFAULT_CONFIRMED_MSG_STATE         LORAMAC_HANDLER_CONFIRMED_MSG
#define LORAWAN_ADR_STATE                           LORAMAC_HANDLER_ADR_ON
#define LORAWAN_DEFAULT_DATA_RATE                   DR_0
#define LORAWAN_DEFAULT_ACTIVATION_TYPE             ACTIVATION_TYPE_OTAA
#define LORAWAN_APP_DATA_BUFFER_MAX_SIZE            242
#define LORAWAN_DEFAULT_PING_SLOT_PERIODICITY       4

**Comment by Th3B1gKahuna** [comment]
BTW @Dana.  Also really appreciate the code!

**Comment by danak6jq** [comment]
> * Activation by ABP
> * Region US915
> * Class A
> * Send Tx on timer (as the title says).
> * APP_TX_DUTYCYCLE of 10s (default value).
>   The issue is that when Tx data is being sent, it stops sending data after a few seconds.
>   Even if the right subband is found, the data is sent just one or two times.
>   Any new idea to try would be so much help.
>   Again, thank you so much for your contribution to this chip!

Do you have access to an ST-Link? It's very difficult to intuit what is happening here; it's not too difficult to connect an ST-Link to the SWD header on the RAK3172E board, enable the debugger in the IOC file, then you can see exactly what's going on in the debugger

**Comment by IvanAmg** [comment]
@danak6jq Thanks a lot for your recommendation.
I've actually fixed my issue, so if it helps future users, I'll describe what I did.
For the debugging part, I'm using a J-link on its compact version.
I knew that this issue could be caused by the Sequencer and timer implementation and its proper functions, so actually trying to debug is kind of hard because you can't really see how the functions are executed, this is caused by the sequencer utility, or at least I didn't find a way to see them while debugging.
Comparing the original End_Node example with the example on this repository, I did find a minor change in the SendTxData() function on the original example.

` if ((JoinLedTimer.IsRunning) && (LmHandlerJoinStatus() == LORAMAC_HANDLER_SET))
   {
     UTIL_TIMER_Stop(&JoinLedTimer);
   }

   status = LmHandlerSend(&AppData, LmHandlerParams.IsTxConfirmed, false);
   if (LORAMAC_HANDLER_SUCCESS == status)
   {
     APP_LOG(TS_ON, VLEVEL_L, "SEND REQUEST\r\n");
   }
   else if (LORAMAC_HANDLER_DUTYCYCLE_RESTRICTED == status)
   {
     nextTxIn = LmHandlerGetDutyCycleWaitTime();
     if (nextTxIn > 0)
     {
       APP_LOG(TS_ON, VLEVEL_L, "Next Tx in  : ~%d second(s)\r\n", (nextTxIn / 1000));
     }
   }`
This small part of the code actually made it work.
Not sure if this part was changed because of your implementation, but at least mine worked adding it.
Also, not sure if this issue was also caused by using a custom board instead of the dev board (RAK5005).
Now I can send data for every duty cycle defined on the .ioc file.
Thanks a lot for your comments @Th3B1gKahuna and @danak6jq.

Again, amazing contribution!

**Comment by danak6jq** [comment]
Excellent work @IvanAmg solving the issue. Thank you!

**Comment by danak6jq** [comment]
@IvanAmg you're using US915 region, what datarate are you running here?

Also, if you want to prepare a PR, I'd be happy to review and merge this.

**Comment by IvanAmg** [comment]
@danak6jq 
The end_node device is set to an adaptive data rate.
Testing with TTN shows me a Data rate: SF10BW125.
Absolutely!
I'll make some adjustments for the PR.

**Comment by danak6jq** [comment]
@IvanAmg - SF10BW125 is DR0, in the US that's limited to 400mS transmit time. So it doesn't surprise me you're running into duty cycle limitation at that DR. I'll have a look and see if I mis-merged the V1.2 example code, too.

Thank you!

**Comment by danak6jq** [comment]
@IvanAmg - please let me know if you get a chance to confirm today's merge has solved this.

**Comment by IvanAmg** [comment]
Hi! @danak6jq 
Apologies for the late reply, it seems that it is working correctly!
I'll keep developing my project, if there's an issue I'll let you know. 
Again, thanks a lot!

**Comment by IvanAmg** [comment]
Also, I think that is important to mention that my settings are:
- Class A
- Activation by ABP
- US915 (tested with TTN SubBand 2)
- LoRaWAN Link version v1.0.3

**Comment by danak6jq** [comment]
@IvanAmg thank you for your help. I added support for 1.0.4 (enabling the context manager and storing context after join) but I believe it's completely innocuous if you select 1.0.3 (and you probably want to de-select the context manager then).
